Repository MOVILES-GRUPO36/5palas12-iOS, pull requests merged in 2024-12, with the labels that each got.

#89 Order changed, Stats working
  5palas12-iOS.xcodeproj/project.pbxproj
  5palas12-iOS.xcodeproj/project.xcworkspace/xcuserdata/santiago.xcuserdatad/UserInterfaceState.xcuserstate
  5palas12-iOS.xcodeproj/xcuserdata/santiago.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  5palas12-iOS/AppDelegate.swift
  5palas12-iOS/BusinessCenter/AddProductView.swift
  5palas12-iOS/BusinessCenter/BusinessProductCardView.swift
  5palas12-iOS/Login/LoginScreen.swift
  5palas12-iOS/Oirders/CreateOrderView.swift
  5palas12-iOS/Oirders/OrderDAO.swift
  5palas12-iOS/Product/CategoriesList.swift
  5palas12-iOS/Product/ProductCardView.swift
  5palas12-iOS/Product/ProductDAO.swift
  5palas12-iOS/Product/ProductModel.swift
  5palas12-iOS/Profile/ProfileStatsView.swift
  5palas12-iOS/Profile/ProfileView.swift
Labels: enhancement

#90 comparing to trees 🌳 ❤️
  5palas12-iOS.xcodeproj/project.xcworkspace/xcuserdata/santiago.xcuserdatad/UserInterfaceState.xcuserstate
  5palas12-iOS/Oirders/CreateOrderView.swift
  5palas12-iOS/Profile/ProfileStatsView.swift
Labels: fix

#92 added micro optimizations
  5palas12-iOS/Profile/ProfileStatsView.swift
Labels: fix

#95 Multi threading and caching implemented
  5palas12-iOS.xcodeproj/project.pbxproj
  5palas12-iOS/BusinessCenter/DeleteBusinessView.swift
  5palas12-iOS/Login/LoginScreen.swift
  5palas12-iOS/NotificationExtensions.swift
  5palas12-iOS/Oirders/CreateOrderView.swift
  5palas12-iOS/Payments/AddCreditCardView.swift
  5palas12-iOS/Profile/ProfileStatsCache.swift
  5palas12-iOS/Profile/ProfileStatsView.swift
  5palas12-iOS/Profile/ProfileStatsViewModel.swift
  5palas12-iOS/Profile/ProfileView.swift
Labels: enhancement

#97 Merge into main from santiago branch NOW DELETE ACCOUNT WORKS, LOGIN FIXED, USERVM BEHAVIOUR FIXED, MULTITHREADING!
  5palas12-iOS/BusinessCenter/BusinessCenterListView.swift
  5palas12-iOS/BusinessCenter/CreateBusinessView.swift
  5palas12-iOS/BusinessCenter/DeleteBusinessView.swift
  5palas12-iOS/Layout/OfflineModeView.swift
  5palas12-iOS/Login/LoginScreen.swift
  5palas12-iOS/Oirders/OrderListView.swift
  5palas12-iOS/Oirders/OrderViewModel.swift
  5palas12-iOS/Profile/ProfileView.swift
  5palas12-iOS/Profile/UserSettingsView.swift
  5palas12-iOS/Restaurant/RestaurantsListView.swift
  5palas12-iOS/Restaurant/SearchView.swift
  5palas12-iOS/User/UserDAO.swift
  5palas12-iOS/User/UserViewModel.swift
  5palas12-iOS/_palas12_iOSApp.swift
Labels: enhancement

#105 Analytics Singleton and multithreading
  5palas12-iOS.xcodeproj/project.pbxproj
  5palas12-iOS.xcodeproj/project.xcworkspace/xcuserdata/santiago.xcuserdatad/UserInterfaceState.xcuserstate
  5palas12-iOS/BusinessCenter/CreateBusinessView.swift
  5palas12-iOS/BusinessCenter/DeleteBusinessView.swift
  5palas12-iOS/FirebaseLogger.swift
  5palas12-iOS/Map/MapView.swift
  5palas12-iOS/Oirders/CreateOrderView.swift
  5palas12-iOS/Oirders/OrderListView.swift
  5palas12-iOS/Profile/EditUserInfoView.swift
  5palas12-iOS/Profile/ProfileStatsView.swift
  5palas12-iOS/Profile/ProfileView.swift
  5palas12-iOS/Profile/UserSettingsView.swift
  5palas12-iOS/Restaurant/RestaurantDetailView.swift
  5palas12-iOS/Restaurant/RestaurantsListView.swift
  5palas12-iOS/Restaurant/SearchView.swift
Labels: enhancement, fix

#106 Sprint4
  5palas12-iOS.xcodeproj/project.pbxproj
  5palas12-iOS.xcodeproj/project.xcworkspace/xcuserdata/juanj.xcuserdatad/UserInterfaceState.xcuserstate
  5palas12-iOS/.DS_Store
  5palas12-iOS/Cart/CartView.swift
  5palas12-iOS/Cart/CartViewModel.swift
  5palas12-iOS/Cart/CheckoutView.swift
  5palas12-iOS/Cart/ProductCartView.swift
  5palas12-iOS/Layout/OfflineModeView.swift
  5palas12-iOS/Layout/TabBarView.swift
  5palas12-iOS/NetworkMonitor.swift
  5palas12-iOS/Orders/CreateOrderView.swift
  5palas12-iOS/Orders/OrderCardView.swift
  5palas12-iOS/Orders/OrderDAO.swift
  5palas12-iOS/Orders/OrderListView.swift
  5palas12-iOS/Orders/OrderModel.swift
  5palas12-iOS/Orders/OrderViewModel.swift
  5palas12-iOS/Orders/TimeManager.swift
  5palas12-iOS/Product/ProductCardView.swift
  5palas12-iOS/Product/ProductListView.swift
  5palas12-iOS/Restaurant/ImageManager.swift
  5palas12-iOS/Restaurant/RestaurantCardView.swift
  5palas12-iOS/Restaurant/RestaurantDetailView.swift
  5palas12-iOS/Restaurant/SearchView.swift
  5palas12-iOS/_palas12_iOSApp.swift
Labels: enhancement, fix
